import type { Metadata } from 'next'
import { Roboto, Cairo } from 'next/font/google'
import './globals.css'
import Header from '@/components/layouts/header'
import Footer from '@/components/layouts/footer'
import ReduxProvider from '@/providers/redux-provider'

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  preload: true
})

const cairo = Cairo({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  preload: true
})

export const metadata: Metadata = {
  title: 'Food ordering',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${roboto.className}`}>
        <ReduxProvider>
          <Header />
          <main className='min-h-screen'>{children}</main>
          <Footer />
        </ReduxProvider>
      </body>
    </html>
  )
}
